dialogId("m-tatinek", "font_small", "Father was right. The linuxers must be mad.")
dialogStr("Tatínek měl pravdu, linuxáci musí být šílení.")
dialogId("v-kdojiny", "font_big", "Who else would make that quantity of barriers.")
dialogStr("Kdo jiný by vytvořil takové množství překážek?")
dialogId("m-zadarmo", "font_small", "To top it all they did it for free.")
dialogStr("A ještě k tomu zadarmo.")

dialogId("m-zamykali", "font_small", "It is clear now, they were locking to protect from us.")
dialogStr("Teď už mi to je jasné, oni se před námi zamykali.")
dialogId("v-horydoly", "font_big", "They were building mountains, valleys, ...")
dialogStr("Stavěli hory, doly...")
dialogId("m-linuxaci", "font_small", "The linuxers!")
dialogStr("Linuxáci!")
dialogId("v-ven", "font_big", "There is only the last task: to put them away.")
dialogStr("Teď už je jen dostat ven.")


dialogId("v-musime", "font_big", "We must put them away.")
dialogStr("Musíme je odtut dostat.")
dialogId("m-radi", "font_small", "I think we should be happy if we manage to get one.")
dialogStr("Myslím, že budeme rádi, když dostaneme ven jednoho.")
dialogId("v-radeji", "font_big", "But if we manage both we should be more happy.")
dialogStr("Ale když odstraníme oba, budeme ještě raději.")

dialogId("m-nemyslis", "font_small", "Do you think that one linuxer out is enough?")
dialogStr("Nemyslíš, že stačí dostat ven jednoho?")
dialogId("v-forkovat", "font_big", "No I don’t. The remaining could fork himself.")
dialogStr("Ne, ten, co by tu zůstal, by se mohl vyforkovat.")


dialogId("m-ukolem", "font_small", "Our goal is to reconcile the linuxers.")
dialogStr("Naším úkolem je usmířit ty linuxáky.")
dialogId("v-alespon", "font_big", "or at least to put them away.")
dialogStr("Nebo je alespoň dostat ven.")


dialogId("m-vykaslat", "font_small", "In my opinion it would be better to give up on the linuxers. Anyway they weren’t in the work description.")
dialogStr("Co takhle se na ty linuxáky prostě vykašlat, vždyť nebyli ani v popisu práce.")
dialogId("v-nabourali", "font_big", "But they hacked this game and we can’t win while they will be there.")
dialogStr("Jenže oni se do té hry nabourali, a doukud je nedostanem ven, nemůžeme vyhrát.")


dialogId("v-snazit", "font_big", "Wow, you had to try hard to put only one linuxer away. You got over the steel construction.")
dialogStr("Teda hráči, ty jsi se musel asi hodně snažit, abys dostal ven jen jednoho linuxáka, podařilo se ti překonat tu ocelovou konstrukci.")
dialogId("m-nestaci", "font_small", "But it isn’t enough to win.")
dialogStr("Ale k vítězství to nestačí.")


dialogId("v-vyrobil", "font_big", "I would like to tell the player to not take this room seriously. After all a linuxer made it.")
dialogStr("Chtěl bych hráče upozornit, aby tuto místnost nebral příliš vážně, vždyť ji vyrobil sám linuxák.")
dialogId("m-sileny", "font_small", "He was probably mad.")
dialogStr("Asi byl šílený.")

dialogId("v-osobne", "font_big", "Player, if you are a linuxer don’t take the madness personally.")
dialogStr("Pokud jsi hráči linuxák, tak si to šílenství neber osobně.")
dialogId("m-ostatni", "font_small", "We aren’t talking about you, we are talking about the others.")
dialogStr("My nemyslíme tebe, my myslíme ty ostatní.")



dialogId("m-samem", "font_small", "It is interesting they are quarreling about the same problems.")
dialogStr("Je zajímavé, že se dokáží přít stále o tom samém.")
dialogId("v-argumenty", "font_big", "And they are using the same arguments.")
dialogStr("A používat stále stejné argumenty.")

dialogId("v-dole", "font_big", "What do you have on the bottom?")
dialogStr("Co to tam dole máš?")
dialogId("2-bubliny", "font_linuxer2", "It is frozen bubbles.")
dialogStr("To jsou mražené bubliny.")
dialogId("1-odpadnou", "font_linuxer1", "If you join three bubbles of the same color they will fall away.")
dialogStr("Když k sobě dostanete tři stejné barvy, tak odpadnou.")

dialogId("m-vtipni", "font_small", "If only the linuxers would be funny.")
dialogStr("Kdyby ti linuxáci byli aspoň vtipní.")
dialogId("1-rozdil", "font_linuxer1", "I know one super joke, do you know the difference between chattr and chmod?")
dialogStr("Já znám jeden super vtip, víš jaký je rozdíl mezi chattr a chmod?")
dialogId("text14", "font_white", "man chattr > 1; man chmod > 2; diff 1 2")
dialogStr("man chattr > 1; man chmod > 2; diff 1 2")
dialogId("2-trapnejsi", "font_linuxer2", "It is more embarrassing than the last comic strip on userfriendly.org.")
dialogStr("To je ještě trapnější než poslední komix na rootu.")
dialogId("1-trilobyte", "font_linuxer1", "And do you know what is eight trilobites? It is one trilobyte.")
dialogStr("A víš, kolik je 8 trilobitů? Jeden trilobyte.")
dialogId("text15", "font_white", "Ha ha ha")
dialogStr("Ha ha ha")



dialogId("2-nezaujata", "font_linuxer2", "Look, this room is trying not be opinionated. There is a penguin at the background. But if there would be logo of Debian, Fedora, ...")
dialogStr("Podívej, jak se snaží být tato místnost nezaujatá, na pozadí je tučňák, ale kdyby tam bylo logo Debianu, Fedory, ...")
dialogId("1-prvni", "font_linuxer1", "Why did you say Debian first?")
dialogStr("Proč jsi řekl jako první Debian?")
dialogId("2-abecedy", "font_linuxer2", "I am reciting by the alphabet.")
dialogStr("Vyjmenovávám podle abecedy.")

dialogId("1-archlinux", "font_linuxer1", "So you should start with Arch Linux.")
dialogStr("To bys měl ale začít Arch linuxem.")
dialogId("2-zapomel", "font_linuxer2", "Sorry, I forgot it. So Arch Linux, Debian, ...")
dialogStr("Pravda, na ten jsem zapomněl, takže Arch linuxu, Debianu, ...")
dialogId("1-podruhe", "font_linuxer1", "Why did you say Debian twice?")
dialogStr("Proč jsi řekl Debian podruhé?")

dialogId("2-naprogramovana", "font_linuxer2", "This game was programmed on Debian.")
dialogStr("Tahle hra byla na Debianu naprogramována.")
dialogId("1-ubuntu", "font_linuxer1", "Why wasn’t it done on Ubuntu?")
dialogStr("Proč ne na Ubuntu?")
dialogId("2-vykradacka", "font_linuxer2", "Ubuntu is only a bad copy of Debian.")
dialogStr("Ubuntu je vykrádačka Debianu, a navíc pěkně nepovedená.")

dialogId("1-zkousel", "font_linuxer1", "Did you try Ubuntu?")
dialogStr("Zkoušel jsi vůbec někdy Ubuntu?")
dialogId("2-root", "font_linuxer2", "No, but it sufficient for me what I heard. Can you log in there as the root?")
dialogStr("Ne, ale stačí mi, co jsem o něm slyšel. Umíš se tam přihlásit jako root?")
dialogId("1-nepotrebuje", "font_linuxer1", "Ubuntu doesn’t need antiquities as the root user is.")
dialogStr("Ubuntu takové starobylosti jako je root vůbec nepotřebuje.")
dialogId("2-postavene", "font_linuxer2", "But it is based on them.")
dialogStr("Ale je na nich postavené.")
dialogId("1-rozhrani", "font_linuxer1", "An interface between user and Unix exists in every distribution.")
dialogStr("Každá distribuce má určité rozhraní mezi Unixem a uživatelem.")

dialogId("2-slackware", "font_linuxer2", "What about Slackware?")
dialogStr("Co takhle Slackware?")
dialogId("1-balickovaci", "font_linuxer1", "Oh yes, but its packaging system is lousy.")
dialogStr("No jo, ale ten má mizerný balíčkovací systém.")
dialogId("2-svuj", "font_linuxer2", "At least it is owned by Slackware.")
dialogStr("Ale aspoň svůj.")


dialogId("2-hadi", "font_linuxer2", "Do you know why are there the snakes?")
dialogStr("Jestli pak víš, proč jsou tu ti hadi?")
dialogId("1-jazyka", "font_linuxer1", "Of course, it is the logo of the best programming language.")
dialogStr("Ovšem, je to logo nejlepšího programovacího jazyka.")
dialogId("2-C", "font_linuxer2", "When did C get logo with snakes?")
dialogStr("Odkdy má C-čko v logu hady?")
dialogId("1-prekonane", "font_linuxer1", "The C is outdated a long time ago. Now there is C++ and Java.")
dialogStr("C-čko uč je dávno překonané, už třeba C-pluspluskem a pak Javou.")
dialogId("2-pomala", "font_linuxer2", "Java is interpreted programming language so it is very slow. Your Python is the same case.")
dialogStr("Java je interpretovaný jazyk, a tak je strašně pomalá, stejně jako ten tvůj Python.")
dialogId("1-pohodli", "font_linuxer1", "I am not interested about speed but the programming comfort.")
dialogStr("Mně nejde o rychlost, ale o pohodlí programátora.")
dialogId("2-prave", "font_linuxer2", "Yes, you aren’t.")
dialogStr("No právě")


dialogId("1-wilber", "font_linuxer1", "Look, Wilber!")
dialogStr("Podívej, Wilber!")
dialogId("2-maskot", "font_linuxer2", "It is the mascot of a great graphic application.")
dialogStr("Maskot jednoho skvělého grafického programu.")
dialogId("1-dohnat", "font_linuxer1", "Which is trying to catch up Photoshop.")
dialogStr("Který se marně snaži dohnat Photoshop.")
dialogId("2-neni", "font_linuxer2", "The GIMP is not Photoshop. It works on a different basis.")
dialogStr("GIMP není Photoshop, funguje na jiných základech.")
dialogId("1-zamaskovali", "font_linuxer1", "The GIMP developers assert it to conceal their inability.")
dialogStr("To jenom tvrdí jeho vývojáři, aby zamaskovali svou neschopnost.")


dialogId("1-nebavi", "font_linuxer1", "I am bored by this music.")
dialogStr("Už mě ta hudba nebaví.")
dialogId("2-skriptik", "font_linuxer2", "Are you unable to write a script for this?")
dialogStr("To sis na to nemoh napsat skriptík?")
dialogId("v-prepinani", "font_big", "And I am bored by the music switching.")
dialogStr("A mne zase nebaví to neustálé přepínání hudby.")

dialogId("text0", "font_white",  "mplayer kufrik.ogg")
dialogStr("mplayer kufrik.ogg")
dialogId("text1", "font_white",  "mplayer menu.ogg")
dialogStr("mplayer menu.ogg")
dialogId("text2", "font_white",  "mplayer rybky01.ogg")
dialogStr("mplayer rybky01.ogg")
dialogId("text3", "font_white",  "mplayer rybky02.ogg")
dialogStr("mplayer rybky02.ogg")
dialogId("text4", "font_white",  "mplayer rybky03.ogg")
dialogStr("mplayer rybky03.ogg")
dialogId("text5", "font_white",  "mplayer rybky04.ogg")
dialogStr("mplayer rybky04.ogg")
dialogId("text6", "font_white",  "mplayer rybky05.ogg")
dialogStr("mplayer rybky05.ogg")
dialogId("text7", "font_white",  "mplayer rybky06.ogg")
dialogStr("mplayer rybky06.ogg")
dialogId("text8", "font_white",  "mplayer rybky07.ogg")
dialogStr("mplayer rybky07.ogg")
dialogId("text9", "font_white",  "mplayer rybky09.ogg")
dialogStr("mplayer rybky09.ogg")
dialogId("text10", "font_white", "mplayer rybky10.ogg")
dialogStr("mplayer rybky10.ogg")
dialogId("text11", "font_white", "mplayer rybky13.ogg")
dialogStr("mplayer rybky13.ogg")
dialogId("text12", "font_white", "mplayer rybky14.ogg")
dialogStr("mplayer rybky14.ogg")
dialogId("text13", "font_white", "mplayer rybky15.ogg")
dialogStr("mplayer rybky15.ogg")
