dialogId("m-tatinek", "font_small", "Father was right. The linuxers must be mad.")
dialogStr("Vater hatte Recht. Die Linuxbenutzer müssen verrückt sein.")
dialogId("v-kdojiny", "font_big", "Who else would make that quantity of barriers.")
dialogStr("Wer sonst würde so viele Hindernisse machen.")
dialogId("m-zadarmo", "font_small", "To top it all they did it for free.")
dialogStr("Noch dazu haben sie es kostenlos gemacht.")

dialogId("m-zamykali", "font_small", "It is clear now, they were locking to protect from us.")
dialogStr("Ich kann es jetzt klar erkennen. Sie schließen sich ein, um sich vor uns zu schützen.")
dialogId("v-horydoly", "font_big", "They were building mountains, valleys, ...")
dialogStr("Sie haben Berge und Täler erschaffen...")
dialogId("m-linuxaci", "font_small", "The linuxers!")
dialogStr("Die Linuxbenutzer!")
dialogId("v-ven", "font_big", "There is only the last task: to put them away.")
dialogStr("Es gibt nur noch eine letzte Aufgabe: Sie wegzubringen.")


dialogId("v-musime", "font_big", "We must put them away.")
dialogStr("Wir müssen sie wegbringen.")
dialogId("m-radi", "font_small", "I think we should be happy if we manage to get one.")
dialogStr("Ich denke, wir sollten froh sein, wenn wir einen schaffen.")
dialogId("v-radeji", "font_big", "But if we manage both we should be more happy.")
dialogStr("Aber wenn wir beide schaffen, sind wir glücklicher.")

dialogId("m-nemyslis", "font_small", "Do you think that one linuxer out is enough?")
dialogStr("Denkst du, daß ein Linuxbenutzer reicht?")
dialogId("v-forkovat", "font_big", "No I don’t. The remaining could fork himself.")
dialogStr("Nein, glaube ich nicht. Der verbleibende könnte sich forken.")


dialogId("m-ukolem", "font_small", "Our goal is to reconcile the linuxers.")
dialogStr("Unser Ziel ist es, die Linuxbenutzer zu versöhnen.")
dialogId("v-alespon", "font_big", "or at least to put them away.")
dialogStr("Oder zumindestens, sie wegzubringen.")


dialogId("m-vykaslat", "font_small", "In my opinion it would be better to give up on the linuxers. Anyway they weren’t in the work description.")
dialogStr("Meiner Meinung nach wäre es besser, die Linuxbenutzer zu lassen. Zumindestens waren sie nicht in der Einsatzbeschreibung.")
dialogId("v-nabourali", "font_big", "But they hacked this game and we can’t win while they will be there.")
dialogStr("Aber sie haben das das Spiel zusammengehackt und wir können nicht gewinnen, so lange sie da sind.")


dialogId("v-snazit", "font_big", "Wow, you had to try hard to put only one linuxer away. You got over the steel construction.")
dialogStr("Wahnsinn, du mußtest dich ziemlich anstrengen, um wenigstens einen Linuxbenutzer wegzubekommen. Du bist über die Stahlkonstruktion gekommen.")
dialogId("m-nestaci", "font_small", "But it isn’t enough to win.")
dialogStr("Aber es reicht nicht, um zu gewinnen.")


dialogId("v-vyrobil", "font_big", "I would like to tell the player to not take this room seriously. After all a linuxer made it.")
dialogStr("Ich würde dem Spieler gerne raten diesen Raum nicht ernst zu nehmen. Alles in allem hat ihn ein Linuxbenutzer gemacht.")
dialogId("m-sileny", "font_small", "He was probably mad.")
dialogStr("Er war möglicherweise verrückt.")

dialogId("v-osobne", "font_big", "Player, if you are a linuxer don’t take the madness personally.")
dialogStr("Spieler, wenn du Linux verwendest, nimm die Verrücktheit nicht so ernst.")
dialogId("m-ostatni", "font_small", "We aren’t talking about you, we are talking about the others.")
dialogStr("Wir reden nicht über dich, wir reden über die anderen.")



dialogId("m-samem", "font_small", "It is interesting they are quarreling about the same problems.")
dialogStr("Es ist interessant, sie zanken über das gleiche Problem.")
dialogId("v-argumenty", "font_big", "And they are using the same arguments.")
dialogStr("Und verwenden die gleichen Argumente.")

dialogId("v-dole", "font_big", "What do you have on the bottom?")
dialogStr("Was hast du da am Boden?")
dialogId("2-bubliny", "font_linuxer2", "It is frozen bubbles.")
dialogStr("Es sind gefrorene Blasen.")
dialogId("1-odpadnou", "font_linuxer1", "If you join three bubbles of the same color they will fall away.")
dialogStr("Wenn du drei Blasen der gleichen Farbe zusammenbringst, werden sie hinunterfallen.")

dialogId("m-vtipni", "font_small", "If only the linuxers would be funny.")
dialogStr("Wenn die Linuxbenutzer wenigstens lustig wären.")
dialogId("1-rozdil", "font_linuxer1", "I know one super joke, do you know the difference between chattr and chmod?")
dialogStr("Ich weiß einen erstklassigen Witz. Kennst du den Unterschied zwischen chattr und chmod?")
dialogId("text14", "font_white", "man chattr > 1; man chmod > 2; diff 1 2")
dialogStr("man chattr > 1; man chmod > 2; diff 1 2")
dialogId("2-trapnejsi", "font_linuxer2", "It is more embarrassing than the last comic strip on userfriendly.org.")
dialogStr("Das ist peinlicher als der letzte userfriendly.org-Comic.")
dialogId("1-trilobyte", "font_linuxer1", "And do you know what is eight trilobites? It is one trilobyte.")
dialogStr("Und weißt du, was acht Trilobiten sind? Ein Trilobyte.")
dialogId("text15", "font_white", "Ha ha ha")
dialogStr("Ha ha ha")



dialogId("2-nezaujata", "font_linuxer2", "Look, this room is trying not be opinionated. There is a penguin at the background. But if there would be logo of Debian, Fedora, ...")
dialogStr("Schau, der Raum versucht neutral zu sein. Da ist ein Pinguin im Hintergrund. Aber wären dort Logos von Debian, Fedora, ...")
dialogId("1-prvni", "font_linuxer1", "Why did you say Debian first?")
dialogStr("Warum hast du Debian zuerst genannt?")
dialogId("2-abecedy", "font_linuxer2", "I am reciting by the alphabet.")
dialogStr("Ich zähle sie alphabetisch auf.")

dialogId("1-archlinux", "font_linuxer1", "So you should start with Arch Linux.")
dialogStr("Dann solltest du mit Arch Linux anfangen.")
dialogId("2-zapomel", "font_linuxer2", "Sorry, I forgot it. So Arch Linux, Debian, ...")
dialogStr("Tut mir leid, habe ich vergessen. Also Arch Linux, Debian, ...")
dialogId("1-podruhe", "font_linuxer1", "Why did you say Debian twice?")
dialogStr("Warum hast du Debian zweimal erwähnt?")

dialogId("2-naprogramovana", "font_linuxer2", "This game was programmed on Debian.")
dialogStr("Das Spiel wurde unter Debian programmiert.")
dialogId("1-ubuntu", "font_linuxer1", "Why wasn’t it done on Ubuntu?")
dialogStr("Warum nicht unter Ubuntu?")
dialogId("2-vykradacka", "font_linuxer2", "Ubuntu is only a bad copy of Debian.")
dialogStr("Ubuntu ist nur eine schlechte Kopie von Debian.")

dialogId("1-zkousel", "font_linuxer1", "Did you try Ubuntu?")
dialogStr("Hast du Ubuntu ausprobiert?")
dialogId("2-root", "font_linuxer2", "No, but it sufficient for me what I heard. Can you log in there as the root?")
dialogStr("Nein, es hat mir gereicht, was ich gehört habe. Kannst du dich da als Root einloggen?")
dialogId("1-nepotrebuje", "font_linuxer1", "Ubuntu doesn’t need antiquities as the root user is.")
dialogStr("Ubuntu benötigt keine Antiquitäten wie root-Benutzer.")
dialogId("2-postavene", "font_linuxer2", "But it is based on them.")
dialogStr("Aber es basiert auf ihnen.")
dialogId("1-rozhrani", "font_linuxer1", "An interface between user and Unix exists in every distribution.")
dialogStr("Eine Schnittstelle zwischen Benutzern und Unix existiert in jeder Distribution.")

dialogId("2-slackware", "font_linuxer2", "What about Slackware?")
dialogStr("Was ist mit Slackware?")
dialogId("1-balickovaci", "font_linuxer1", "Oh yes, but its packaging system is lousy.")
dialogStr("Ist ok, aber das Paketsystem ist lausig..")
dialogId("2-svuj", "font_linuxer2", "At least it is owned by Slackware.")
dialogStr("Es gehört ihnen wenigstens.")


dialogId("2-hadi", "font_linuxer2", "Do you know why are there the snakes?")
dialogStr("Weißt du, warum dort Schlangen sind?")
dialogId("1-jazyka", "font_linuxer1", "Of course, it is the logo of the best programming language.")
dialogStr("Natürlich. Sie sind das Logo der besten Programmiersprache.")
dialogId("2-C", "font_linuxer2", "When did C get logo with snakes?")
dialogStr("Seit wann hat C Schlangen als Logo?")
dialogId("1-prekonane", "font_linuxer1", "The C is outdated a long time ago. Now there is C++ and Java.")
dialogStr("C ist seit langer Zeit veraltet. Jetzt gibt es C++ und Java.")
dialogId("2-pomala", "font_linuxer2", "Java is interpreted programming language so it is very slow. Your Python is the same case.")
dialogStr("Java ist als interpretierte Sprache sehr langsam. Genau wie dein Python.")
dialogId("1-pohodli", "font_linuxer1", "I am not interested about speed but the programming comfort.")
dialogStr("Ich bin nicht an der Geschwindigkeit interessiert, sondern am Programmierkomfort.")
dialogId("2-prave", "font_linuxer2", "Yes, you aren’t.")
dialogStr("Doch, bist du nicht.")


dialogId("1-wilber", "font_linuxer1", "Look, Wilber!")
dialogStr("Schau, Wilber!")
dialogId("2-maskot", "font_linuxer2", "It is the mascot of a great graphic application.")
dialogStr("Es ist das Mascotchen einer großartigen Graphikanwendung.")
dialogId("1-dohnat", "font_linuxer1", "Which is trying to catch up Photoshop.")
dialogStr("Welche versucht Photoshop zu erreichen.")
dialogId("2-neni", "font_linuxer2", "The GIMP is not Photoshop. It works on a different basis.")
dialogStr("GIMP ist nicht Photoshop. Es arbeitet total anders.")
dialogId("1-zamaskovali", "font_linuxer1", "The GIMP developers assert it to conceal their inability.")
dialogStr("Die GIMP-Entwickler versuchen ihre Unfähigkeit zu verbergen.")


dialogId("1-nebavi", "font_linuxer1", "I am bored by this music.")
dialogStr("Die Musik langweilt mich.")
dialogId("2-skriptik", "font_linuxer2", "Are you unable to write a script for this?")
dialogStr("Kannst du kein Skript dafür schreiben?")
dialogId("v-prepinani", "font_big", "And I am bored by the music switching.")
dialogStr("Und die Musikwechsel langweilen mich.")

dialogId("text0", "font_white",  "mplayer kufrik.ogg")
dialogStr("mplayer kufrik.ogg")
dialogId("text1", "font_white",  "mplayer menu.ogg")
dialogStr("mplayer menu.ogg")
dialogId("text2", "font_white",  "mplayer rybky01.ogg")
dialogStr("mplayer rybky01.ogg")
dialogId("text3", "font_white",  "mplayer rybky02.ogg")
dialogStr("mplayer rybky02.ogg")
dialogId("text4", "font_white",  "mplayer rybky03.ogg")
dialogStr("mplayer rybky03.ogg")
dialogId("text5", "font_white",  "mplayer rybky04.ogg")
dialogStr("mplayer rybky04.ogg")
dialogId("text6", "font_white",  "mplayer rybky05.ogg")
dialogStr("mplayer rybky05.ogg")
dialogId("text7", "font_white",  "mplayer rybky06.ogg")
dialogStr("mplayer rybky06.ogg")
dialogId("text8", "font_white",  "mplayer rybky07.ogg")
dialogStr("mplayer rybky07.ogg")
dialogId("text9", "font_white",  "mplayer rybky09.ogg")
dialogStr("mplayer rybky09.ogg")
dialogId("text10", "font_white", "mplayer rybky10.ogg")
dialogStr("mplayer rybky10.ogg")
dialogId("text11", "font_white", "mplayer rybky13.ogg")
dialogStr("mplayer rybky13.ogg")
dialogId("text12", "font_white", "mplayer rybky14.ogg")
dialogStr("mplayer rybky14.ogg")
dialogId("text13", "font_white", "mplayer rybky15.ogg")
dialogStr("mplayer rybky15.ogg")
